const FETCH_MOVIE_LIST_REQUEST = 'FETCH_MOVIE_LIST_REQUEST';
const FETCH_MOVIE_LIST_SUCCEEDED = 'FETCH_MOVIE_LIST_SUCCEEDED';
const FETCH_MOVIE_LIST_FAILED = 'FETCH_MOVIE_LIST_FAILED';

const FETCH_INTERNET_CONNECTION_REQUEST = 'FETCH_INTERNET_CONNECTION_REQUEST'
const FETCH_INTERNET_CONNECTION_SUCCEEDED = 'FETCH_INTERNET_CONNECTION_SUCCEEDED'
const FETCH_INTERNET_CONNECTION_FAILED = 'FETCH_INTERNET_CONNECTION_FAILED'

export {
    FETCH_MOVIE_LIST_REQUEST,
    FETCH_MOVIE_LIST_SUCCEEDED,
    FETCH_MOVIE_LIST_FAILED,
    FETCH_INTERNET_CONNECTION_REQUEST,
    FETCH_INTERNET_CONNECTION_SUCCEEDED,
    FETCH_INTERNET_CONNECTION_FAILED
}

