const FETCH_MOVIE_LIST_REQUEST = 'FETCH_MOVIE_LIST_REQUEST';
const FETCH_MOVIE_LIST_SUCCEEDED = 'FETCH_MOVIE_LIST_SUCCEEDED';
const FETCH_MOVIE_LIST_FAILED = 'FETCH_MOVIE_LIST_FAILED';

export {
    FETCH_MOVIE_LIST_REQUEST,
    FETCH_MOVIE_LIST_SUCCEEDED,
    FETCH_MOVIE_LIST_FAILED,
}

